### ISSUE TITLE
How to get images?

### ISSUE THREAD

**Issue by jolinxql** [andrewliao11/env-aware-program-gen#1]
Hi,
As README.md shows, there are two folders under `demonstration` folder.
```
 ├── demonstration
 │   ├── images
 │   └── images_augment
```
How or where can I get them?

**Comment by andrewliao11** [comment]
Given the script and the corresponding environment graph, you can easily get the images by following the instruction [here](https://github.com/xavierpuigf/virtualhome). 
Since we are planning to release the demonstration as well, please wait a little bit if you are not in a hurry :)

**Comment by jolinxql** [comment]
Thank you. Yes, I'm also trying to make use of scripts in the virtualhome repo. 
But I'm wondering what camera_indexes you used for generating those images? Is [-7] enough?
It would be very helpful if you can provide some sample images or small code snippets as a hint before releasing the whole dataset.

**Comment by ByZ0e** [comment]
Hi, have you released the demonstration yet? And can you specify how to get images? The instruction is too complex.
