### ISSUE TITLE
pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by CharlesQ9** [andrewliao11/env-aware-program-gen#6]
On the line 5,
pkg-resources==0.0.0
It that a slip of pen? Thanks!

**Comment by andrewliao11** [comment]
It's dumped by 
```
pip freeze > requirements.txt
```
Not sure why it exists. Do you mind creating a pull request? or I can directly fix it. Thanks!

**Comment by Charles-Qiu** [comment]
> It's dumped by
> 
> ```
> pip freeze > requirements.txt
> ```
> 
> Not sure why it exists. Do you mind creating a pull request? or I can directly fix it. Thanks!

Thanks for your explanation!
Sorry that I don't know how to create a pull request.
