### ISSUE TITLE
Trying to produce augmented datasets

### ISSUE THREAD

**Issue by CharlesQ9** [andrewliao11/env-aware-program-gen#7]
When I run the program for producing augmented dataset following https://github.com/xavierpuigf/virtualhome#script-augmentation
cd dataset_utils
python augment_dataset_locations.py

However,
Traceback (most recent call last):
  File "augment_dataset_locations.py", line 239, in <module>
    augment_dataset({}, programs)
  File "augment_dataset_locations.py", line 188, in augment_dataset
    {})
  File "../simulation/evolving_graph/check_programs.py", line 226, in check_script
    graph_dict = utils.load_graph_dict(graph_path)
  File "../simulation/evolving_graph/utils.py", line 82, in load_graph_dict
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../example_graphs/TrimmedTestScene2_graph.json'

I then download http://virtual-home.org/release/programs/augment_location.zip but I don't know which file should be TrimmedTestScene2_graph.json.

**Comment by CharlesQ9** [comment]
├── augment_programs
    │   ├── augment_exception
    │   └── augment_location

Is the folder augment_location just this link  http://virtual-home.org/release/programs/augment_location.zip?

**Comment by andrewliao11** [comment]
The files `TrimmedTestScene*_graph.json` are [here](https://github.com/andrewliao11/env-aware-program-gen/tree/master/dataset/VirtualHome-Env/resources). Please link the files to the specified paths.

**Comment by CharlesQ9** [comment]
> ```
> ├── augment_programs
> │   ├── augment_exception
> │   └── augment_location
> ```
> 
> Is the folder augment_location just this link http://virtual-home.org/release/programs/augment_location.zip?

How about this? Is this right?

**Comment by andrewliao11** [comment]
The files [here](http://virtual-home.org/release/programs/augment_location.zip) are the generated augmented datasets. and the ones that I posted [here](https://github.com/andrewliao11/env-aware-program-gen/issues/7#issuecomment-925360306) are the sources files.
